Add new config option for collections
UniversalViewer/universalviewer pull request #1107
Opened 2024-09-09 11:25 UTC by Saira-A

#### Description of what you did:

Added a new option called "defaultToTreeIfCollection" to the config so that the left panel defaults to Index rather than Thumbnails if the item is a collection, so the tree view of manifests within the collection is visible by default

2024-09-19 15:01 UTC, Saira-A commented
Thanks @demiankatz! I refactored it but I'm not sure about line 286 so let me know if there's a better way :)

2024-09-19 16:06 UTC, demiankatz commented
Thanks, @Saira-A! Regarding line 286, I think it would probably make sense to move the remaining logic inside defaultToThumbsView so the logic is consistent. Maybe you could change lines 622-624 to something like:

```
    // Default to tree view if the manifest is a collection and either the "default to tree if collection" setting is
    // on, or the tree has nav dates (which always require a tree):
    if (this.isCollection() && (defaultToTreeIfCollection || this.extension.helper.treeHasNavDates(treeData))) {
      return false;
    }
```

I'm not really familiar with the "nav dates" functionality, though, so I'm basing this suggestion on a logical refactoring of the code more than on direct experience with the intent behind the code... so please take my suggestion with the appropriate grain of salt.

2024-10-08 13:33 UTC, demiankatz requested changes
Thanks, @Saira-A! This looks good to me now (though I haven't personally tested it); see below for some suggestions that might help clarify the relationships between the configuration settings. Feel free to accept, modify or ignore as you see fit. :-)

2024-10-08 13:33 UTC, demiankatz commented on src/content-handlers/iiif/extensions/config/ContentLeftPanel.ts
>    /** Number of items to default to tree view */
```suggestion
  /** Number of items to default to tree view (when defaultToTreeEnabled = true; defaults to 0) */
```

2024-10-08 13:33 UTC, demiankatz commented on src/content-handlers/iiif/extensions/config/ContentLeftPanel.ts
> +   /** Determines if collection should default to tree view */
```suggestion
   /** Determines if collection should default to tree view (even if defaultToTreeEnabled = false) */
```

2024-10-09 10:39 UTC, Saira-A commented
Makes sense, thanks @demiankatz!

2024-10-09 10:57 UTC, demiankatz approved these changes
Thanks, @Saira-A, I'm approving this so merging won't be blocked and because the logic makes sense to me -- but it would probably be a good idea to get some hands-on testing on this before merging it if anyone has time (assuming @LanieOkorodudu hasn't already done it). :-)

2024-10-09 11:32 UTC, LanieOkorodudu commented
> Thanks, @Saira-A, I'm approving this so merging won't be blocked and because the logic makes sense to me -- but it would probably be a good idea to get some hands-on testing on this before merging it if anyone has time (assuming @LanieOkorodudu hasn't already done it)

I just test it and it should be fine to merge @demiankatz

2024-10-09 11:48 UTC, merged

2024-10-09 11:49 UTC, demiankatz commented
Thanks, @LanieOkorodudu!